//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ANTLR/LowLevelAssembly.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LowLevelAssemblyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ILowLevelAssemblyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LowLevelAssemblyParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SET</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSET([NotNull] LowLevelAssemblyParser.SETContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOV_ALU_IN</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOV_ALU_IN([NotNull] LowLevelAssemblyParser.MOV_ALU_INContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOV_ALU_OUT</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOV_ALU_OUT([NotNull] LowLevelAssemblyParser.MOV_ALU_OUTContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOV_ALU_C_TO_AB</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOV_ALU_C_TO_AB([NotNull] LowLevelAssemblyParser.MOV_ALU_C_TO_ABContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SHL</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSHL([NotNull] LowLevelAssemblyParser.SHLContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SHR</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSHR([NotNull] LowLevelAssemblyParser.SHRContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SAR</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSAR([NotNull] LowLevelAssemblyParser.SARContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RCL</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRCL([NotNull] LowLevelAssemblyParser.RCLContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RCR</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRCR([NotNull] LowLevelAssemblyParser.RCRContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OR</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOR([NotNull] LowLevelAssemblyParser.ORContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ADD</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitADD([NotNull] LowLevelAssemblyParser.ADDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ADC</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitADC([NotNull] LowLevelAssemblyParser.ADCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUB</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUB([NotNull] LowLevelAssemblyParser.SUBContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SBB</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSBB([NotNull] LowLevelAssemblyParser.SBBContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>XOR</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXOR([NotNull] LowLevelAssemblyParser.XORContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AND</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAND([NotNull] LowLevelAssemblyParser.ANDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NOT</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNOT([NotNull] LowLevelAssemblyParser.NOTContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NEG</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNEG([NotNull] LowLevelAssemblyParser.NEGContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOV8</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOV8([NotNull] LowLevelAssemblyParser.MOV8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NOP</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNOP([NotNull] LowLevelAssemblyParser.NOPContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOV</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOV([NotNull] LowLevelAssemblyParser.MOVContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOV16</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOV16([NotNull] LowLevelAssemblyParser.MOV16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOAD</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOAD([NotNull] LowLevelAssemblyParser.LOADContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STORE</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTORE([NotNull] LowLevelAssemblyParser.STOREContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SAVE_FLAGS</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSAVE_FLAGS([NotNull] LowLevelAssemblyParser.SAVE_FLAGSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RESTORE_FLAGS</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRESTORE_FLAGS([NotNull] LowLevelAssemblyParser.RESTORE_FLAGSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FLAGS_TO_OUTBUFFER</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFLAGS_TO_OUTBUFFER([NotNull] LowLevelAssemblyParser.FLAGS_TO_OUTBUFFERContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STORE_FLAGS</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTORE_FLAGS([NotNull] LowLevelAssemblyParser.STORE_FLAGSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INBUFFER_TO_FLAGS</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINBUFFER_TO_FLAGS([NotNull] LowLevelAssemblyParser.INBUFFER_TO_FLAGSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOAD_FLAGS</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOAD_FLAGS([NotNull] LowLevelAssemblyParser.LOAD_FLAGSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BIT16_ADDER</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBIT16_ADDER([NotNull] LowLevelAssemblyParser.BIT16_ADDERContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JMP_LABEL</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJMP_LABEL([NotNull] LowLevelAssemblyParser.JMP_LABELContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JMP</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJMP([NotNull] LowLevelAssemblyParser.JMPContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JZ</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJZ([NotNull] LowLevelAssemblyParser.JZContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JNZ</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJNZ([NotNull] LowLevelAssemblyParser.JNZContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JNS</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJNS([NotNull] LowLevelAssemblyParser.JNSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>JNC</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJNC([NotNull] LowLevelAssemblyParser.JNCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CALL</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCALL([NotNull] LowLevelAssemblyParser.CALLContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RET</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRET([NotNull] LowLevelAssemblyParser.RETContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IN</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIN([NotNull] LowLevelAssemblyParser.INContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OUT</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOUT([NotNull] LowLevelAssemblyParser.OUTContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INT</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINT([NotNull] LowLevelAssemblyParser.INTContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HLT</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHLT([NotNull] LowLevelAssemblyParser.HLTContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DATA</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDATA([NotNull] LowLevelAssemblyParser.DATAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MACRO</c>
	/// labeled alternative in <see cref="LowLevelAssemblyParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMACRO([NotNull] LowLevelAssemblyParser.MACROContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.register_8bit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegister_8bit([NotNull] LowLevelAssemblyParser.Register_8bitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.register_16bit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegister_16bit([NotNull] LowLevelAssemblyParser.Register_16bitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.register_ab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegister_ab([NotNull] LowLevelAssemblyParser.Register_abContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.out_port_8bit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOut_port_8bit([NotNull] LowLevelAssemblyParser.Out_port_8bitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.port_8bit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort_8bit([NotNull] LowLevelAssemblyParser.Port_8bitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.plus_sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlus_sign([NotNull] LowLevelAssemblyParser.Plus_signContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.minus_sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinus_sign([NotNull] LowLevelAssemblyParser.Minus_signContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LowLevelAssemblyParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] LowLevelAssemblyParser.IntContext context);
}
